### ISSUE TITLE
getFeildText

### ISSUE THREAD

**Issue by dalinxz** [gajeshbhat/django-experiments#1]
Hey just a question, on the getFeildText within the SendMail views.py module, was this simply a typo, or was it spelt as getFeildText in lieu of getFieldText for a particular reason?

I assume it's simply a typo but just want to make sure.

Thanks again, your tutorial was very helpful Gajesh!

Sincerely, 
Ali

**Comment by gajeshbhat** [comment]
I think it was a typo. Thanks for pointing it out.

Best,
Gajesh
