### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by typonaut** [gajeshbhat/django-experiments#2]
Gajesh, I'd like to integrate your demo with my project, but you've given no licensing information. Is it open source?

**Comment by gajeshbhat** [comment]
Hello,

License is GPL 3.0. Feel free to integrate my work in your project. As a
courtesy please link back the repo in your documentation or reports.

Best,
Gajesh

>

**Comment by typonaut** [comment]
Sure, no problem, thanks for getting back to me so quickly.
